/**
 * GitHub API helpers
 *
 * 用于把用户上传的 SKILL.md 提交到你自己的 skills repo，并创建 PR。
 *
 * 所需环境变量：
 *   GITHUB_TOKEN          — Personal Access Token，需要 repo 权限
 *   GITHUB_SKILLS_OWNER   — 你的 GitHub 用户名，如 "yourusername"
 *   GITHUB_SKILLS_REPO    — 你的 skills repo 名，如 "askill-skills"
 *   GITHUB_BASE_BRANCH    — 默认分支，通常是 "main"
 */

const OWNER  = process.env.GITHUB_SKILLS_OWNER!
const REPO   = process.env.GITHUB_SKILLS_REPO!
const BASE   = process.env.GITHUB_BASE_BRANCH ?? 'main'
const TOKEN  = process.env.GITHUB_TOKEN!

const GH_API = 'https://api.github.com'

function ghHeaders() {
  return {
    Authorization: `Bearer ${TOKEN}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28',
  }
}

async function ghFetch(path: string, options?: RequestInit) {
  const res = await fetch(`${GH_API}${path}`, {
    ...options,
    headers: { ...ghHeaders(), ...(options?.headers ?? {}) },
  })
  const data = await res.json()
  if (!res.ok) throw new Error(data.message ?? `GitHub API error ${res.status}`)
  return data
}

// ─── 获取分支最新 commit SHA ──────────────────────────────────────────────────
async function getLatestSha(branch: string): Promise<string> {
  const data = await ghFetch(`/repos/${OWNER}/${REPO}/git/refs/heads/${branch}`)
  return data.object.sha
}

// ─── 创建新分支 ───────────────────────────────────────────────────────────────
async function createBranch(branch: string, fromSha: string) {
  await ghFetch(`/repos/${OWNER}/${REPO}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: fromSha }),
  })
}

// ─── 创建文件到指定分支 ────────────────────────────────────────────────────────
async function createFile(
  branch: string,
  path: string,
  content: string,
  message: string
) {
  const encoded = Buffer.from(content, 'utf-8').toString('base64')
  await ghFetch(`/repos/${OWNER}/${REPO}/contents/${path}`, {
    method: 'PUT',
    body: JSON.stringify({
      message,
      content: encoded,
      branch,
    }),
  })
}

// ─── 创建 Pull Request ────────────────────────────────────────────────────────
async function createPR(
  head: string,
  title: string,
  body: string
): Promise<{ number: number; html_url: string }> {
  const data = await ghFetch(`/repos/${OWNER}/${REPO}/pulls`, {
    method: 'POST',
    body: JSON.stringify({ title, body, head, base: BASE }),
  })
  return { number: data.number, html_url: data.html_url }
}

// ─── 主函数：提交 skill 并创建 PR ─────────────────────────────────────────────
export interface SubmitSkillParams {
  slug: string           // skill 唯一 slug，如 "gmail-summarizer"
  markdown: string       // SKILL.md 完整内容
  authorUsername: string // 提交者 GitHub 用户名
  description: string    // 简短描述（用于 PR body）
}

export interface SubmitSkillResult {
  prNumber: number
  prUrl: string
  branch: string
}

export async function submitSkillToGitHub(
  params: SubmitSkillParams
): Promise<SubmitSkillResult> {
  const { slug, markdown, authorUsername, description } = params

  // 1. 生成唯一分支名（避免冲突）
  const ts     = Date.now()
  const branch = `skill/${slug}-${ts}`

  // 2. 获取 base 分支最新 SHA
  const baseSha = await getLatestSha(BASE)

  // 3. 基于 main 创建新分支
  await createBranch(branch, baseSha)

  // 4. 把 SKILL.md 写入新分支
  await createFile(
    branch,
    `skills/${slug}/SKILL.md`,
    markdown,
    `feat: add skill "${slug}" by @${authorUsername}`
  )

  // 5. 创建 PR（待你审核后合并）
  const pr = await createPR(
    branch,
    `[Skill] ${slug}`,
    [
      `**Submitted by:** @${authorUsername}`,
      `**Skill slug:** \`${slug}\``,
      '',
      `**Description:** ${description}`,
      '',
      '---',
      '_Auto-generated by Askill upload system_',
    ].join('\n')
  )

  return { prNumber: pr.number, prUrl: pr.html_url, branch }
}